import { Dish } from './types';

// 使用 loremflickr 按菜品名称搜索配图，可靠性更高
const img = (name: string, extra: string = '') => {
  const keyword = encodeURIComponent(name + (extra ? ',' + extra : ''));
  return `https://loremflickr.com/600/400/${keyword}?lock=${Math.floor(Math.random() * 99999)}`;
};

// 封面图（按菜名搜索）
const cover = (name: string) => img(name, 'food');

// 步骤图（按步骤关键词搜索）
const stepImg = (name: string, step: number, title: string) => {
  const keyword = encodeURIComponent(`${name},${title},food,cooking`);
  return `https://loremflickr.com/600/400/${keyword}?lock=${Math.floor(Math.random() * 99999)}`;
};

export const dishesData: Dish[] = [
  // ========== 家常菜 ==========
  {
    id: 'd1', name: '红烧肉', category: '家常菜', emoji: '🥩', liked: true,
    tags: ['硬菜', '下饭', '宴客'],
    addedAt: '2026-01-01',
    image: cover('红烧肉'),
    prepTime: '15分钟', cookTime: '60分钟', servings: 3,
    difficulty: '中等',
    description: '肥而不腻、入口即化的经典红烧肉',
    ingredients: ['五花肉 500g', '冰糖 30g', '生抽 2勺', '老抽 1勺', '料酒 2勺', '八角 2个', '桂皮 1小块', '姜片 5片', '葱段 适量', '盐 适量'],
    steps: [
      { step: 1, title: '处理五花肉', description: '五花肉切成3cm见方的块，冷水下锅焯水去血沫，捞出沥干备用。', image: stepImg('红烧肉', 1, '焯水五花肉') },
      { step: 2, title: '炒糖色', description: '锅中放少许油，下冰糖小火慢慢炒化，炒至枣红色起小泡时下入肉块翻炒上色。', image: stepImg('红烧肉', 2, '炒糖色') },
      { step: 3, title: '加入调料炖煮', description: '加入姜片、葱段、八角、桂皮，倒入料酒、生抽、老抽，加开水没过肉块，大火烧开转小火炖50分钟。', image: stepImg('红烧肉', 3, '红烧肉炖煮') },
      { step: 4, title: '大火收汁', description: '炖至肉酥软，汤汁浓稠时，开大火收汁，边收边翻动让肉块均匀裹上糖色，汤汁收到浓稠即可出锅。', image: stepImg('红烧肉', 4, '收汁红烧肉') },
    ],
  },
  {
    id: 'd2', name: '番茄炒鸡蛋', category: '家常菜', emoji: '🍅', liked: true,
    tags: ['快手', '清淡', '下饭'],
    addedAt: '2026-01-01',
    image: cover('番茄炒蛋'),
    prepTime: '5分钟', cookTime: '10分钟', servings: 2,
    difficulty: '简单',
    description: '酸甜可口，国民下饭菜',
    ingredients: ['鸡蛋 3个', '番茄 2个', '盐 1茶匙', '糖 1茶匙', '葱花 适量', '油 适量'],
    steps: [
      { step: 1, title: '打蛋炒蛋', description: '鸡蛋打散加少许盐搅匀。热锅宽油，倒入蛋液快速翻炒成大块盛出。', image: stepImg('番茄炒蛋', 1, '炒鸡蛋') },
      { step: 2, title: '炒番茄', description: '番茄切块，锅中留底油，下番茄块翻炒出汁，可加少许水帮助出汁。', image: stepImg('番茄炒蛋', 2, '炒番茄') },
      { step: 3, title: '合炒调味', description: '倒入炒好的鸡蛋，加盐和糖调味，翻炒均匀，撒上葱花即可出锅。', image: stepImg('番茄炒蛋', 3, '番茄炒蛋成品') },
    ],
  },
  {
    id: 'd3', name: '蒜蓉西兰花', category: '家常菜', emoji: '🥦', liked: false,
    tags: ['素菜', '清淡', '健康'],
    addedAt: '2026-01-01',
    image: cover('西兰花'),
    prepTime: '10分钟', cookTime: '5分钟', servings: 2,
    difficulty: '简单',
    description: '翠绿爽口，营养丰富的快手素菜',
    ingredients: ['西兰花 1颗', '蒜末 3瓣', '盐 适量', '蚝油 1勺', '油 适量'],
    steps: [
      { step: 1, title: '处理西兰花', description: '西兰花切小朵，浸泡盐水10分钟去农药，洗净备用。', image: stepImg('西兰花', 1, '西兰花切朵') },
      { step: 2, title: '焯水断生', description: '锅中烧开水，加少许盐和油，放入西兰花焯水1分钟，捞出过凉水保持翠绿。', image: stepImg('西兰花', 2, '西兰花焯水') },
      { step: 3, title: '爆香翻炒', description: '热锅宽油，下蒜末爆香，倒入西兰花快速翻炒，加蚝油和盐调味即可出锅。', image: stepImg('西兰花', 3, '蒜蓉西兰花') },
    ],
  },
  {
    id: 'd4', name: '可乐鸡翅', category: '家常菜', emoji: '🍗', liked: true,
    tags: ['甜口', '孩子爱', '宴客'],
    addedAt: '2026-01-01',
    image: cover('可乐鸡翅'),
    prepTime: '10分钟', cookTime: '30分钟', servings: 3,
    difficulty: '简单',
    description: '甜香浓郁，鸡翅嫩滑入味',
    ingredients: ['鸡翅中 10个', '可乐 330ml', '生抽 2勺', '老抽 1勺', '姜片 5片', '料酒 1勺', '白芝麻 少许'],
    steps: [
      { step: 1, title: '处理鸡翅', description: '鸡翅洗净，两面各划两刀方便入味，冷水下锅焯水去腥，捞出沥干。', image: stepImg('鸡翅', 1, '处理鸡翅') },
      { step: 2, title: '煎制鸡翅', description: '锅中少许油，将鸡翅煎至两面金黄。', image: stepImg('鸡翅', 2, '煎鸡翅') },
      { step: 3, title: '可乐炖煮', description: '加入姜片，倒入可乐、生抽、老抽、料酒，大火烧开后转小火炖20分钟。', image: stepImg('可乐鸡翅', 3, '可乐炖鸡翅') },
      { step: 4, title: '收汁出锅', description: '大火收汁至浓稠，汤汁裹满鸡翅，撒上白芝麻即可。', image: stepImg('可乐鸡翅', 4, '可乐鸡翅成品') },
    ],
  },
  {
    id: 'd5', name: '酸辣土豆丝', category: '家常菜', emoji: '🥔', liked: true,
    tags: ['酸辣', '下饭', '快手'],
    addedAt: '2026-01-01',
    image: cover('酸辣土豆丝'),
    prepTime: '10分钟', cookTime: '5分钟', servings: 2,
    difficulty: '简单',
    description: '酸辣爽脆，下饭神器',
    ingredients: ['土豆 2个', '干辣椒 5个', '花椒 10粒', '蒜末 适量', '白醋 2勺', '盐 适量', '葱花 少许'],
    steps: [
      { step: 1, title: '切土豆丝', description: '土豆去皮切成均匀的细丝，放入清水中浸泡去除多余淀粉。', image: stepImg('土豆丝', 1, '切土豆丝') },
      { step: 2, title: '焯水过凉', description: '锅中烧水，水开后下土豆丝焯水30秒，捞出过凉水保持脆爽。', image: stepImg('土豆丝', 2, '土豆丝焯水') },
      { step: 3, title: '爆炒调味', description: '热锅宽油，下花椒、干辣椒、蒜末爆香，倒入土豆丝大火快炒，加白醋、盐调味，撒葱花出锅。', image: stepImg('酸辣土豆丝', 3, '酸辣土豆丝成品') },
    ],
  },
  {
    id: 'd6', name: '宫保鸡丁', category: '家常菜', emoji: '🐔', liked: true,
    tags: ['香辣', '甜酸', '下饭'],
    addedAt: '2026-01-01',
    image: cover('宫保鸡丁'),
    prepTime: '15分钟', cookTime: '10分钟', servings: 3,
    difficulty: '中等',
    description: '鸡丁嫩滑，花生酥脆，酸甜香辣',
    ingredients: ['鸡胸肉 300g', '花生米 50g', '干辣椒 8个', '花椒 1小把', '葱段 适量', '姜末 适量', '蒜末 适量', '生抽 1勺', '醋 1勺', '糖 1勺', '淀粉 适量'],
    steps: [
      { step: 1, title: '处理鸡丁', description: '鸡胸肉切1.5cm丁，加盐、料酒、淀粉抓匀腌制15分钟。', image: stepImg('鸡胸肉', 1, '切鸡丁') },
      { step: 2, title: '调宫保汁', description: '生抽、醋、糖、淀粉、少许水调匀成宫保汁备用。', image: stepImg('宫保鸡丁', 2, '调料汁') },
      { step: 3, title: '炒香花生', description: '冷锅冷油下花生米，小火慢慢炸至金黄酥脆，捞出备用。', image: stepImg('花生米', 3, '炸花生') },
      { step: 4, title: '爆炒鸡丁', description: '热锅宽油，下鸡丁滑炒至变色盛出。锅中留底油，下花椒、干辣椒、葱姜蒜末爆香，倒回鸡丁，淋入宫保汁快炒，最后撒入花生米翻匀出锅。', image: stepImg('宫保鸡丁', 4, '宫保鸡丁成品') },
    ],
  },
  {
    id: 'd7', name: '鱼香肉丝', category: '家常菜', emoji: '🐟', liked: true,
    tags: ['酸甜', '下饭', '经典'],
    addedAt: '2026-01-01',
    image: cover('鱼香肉丝'),
    prepTime: '15分钟', cookTime: '10分钟', servings: 3,
    difficulty: '中等',
    description: '酸甜微辣，经典川味家常菜',
    ingredients: ['猪里脊 300g', '木耳 30g', '胡萝卜 1根', '青椒 1个', '泡椒 3个', '葱姜蒜末 适量', '生抽 1勺', '醋 1勺', '糖 1.5勺', '淀粉 适量', '豆瓣酱 1勺'],
    steps: [
      { step: 1, title: '切丝腌制', description: '里脊肉切丝，加盐、料酒、淀粉抓匀腌制。木耳、胡萝卜、青椒切丝备用。', image: stepImg('肉丝', 1, '切肉丝') },
      { step: 2, title: '调鱼香汁', description: '生抽、醋、糖、淀粉、水调匀成鱼香汁备用。', image: stepImg('鱼香肉丝', 2, '调鱼香汁') },
      { step: 3, title: '滑炒肉丝', description: '热锅宽油，下肉丝滑炒至变色盛出。锅中留底油，下豆瓣酱、泡椒、葱姜蒜末炒出红油。', image: stepImg('鱼香肉丝', 3, '炒肉丝') },
      { step: 4, title: '合炒出锅', description: '下木耳、胡萝卜、青椒丝翻炒，倒回肉丝，淋入鱼香汁快速翻匀即可出锅。', image: stepImg('鱼香肉丝', 4, '鱼香肉丝成品') },
    ],
  },
  {
    id: 'd8', name: '地三鲜', category: '家常菜', emoji: '🍆', liked: false,
    tags: ['素菜', '下饭', '东北'],
    addedAt: '2026-01-01',
    image: cover('地三鲜'),
    prepTime: '15分钟', cookTime: '15分钟', servings: 3,
    difficulty: '中等',
    description: '茄子、土豆、青椒的东北经典组合',
    ingredients: ['茄子 1个', '土豆 1个', '青椒 2个', '蒜末 适量', '生抽 2勺', '老抽 1勺', '糖 半勺', '淀粉 适量', '油 大量'],
    steps: [
      { step: 1, title: '处理食材', description: '茄子、土豆切滚刀块，青椒切块。茄子提前用盐腌制10分钟去水分。', image: stepImg('地三鲜', 1, '切菜备料') },
      { step: 2, title: '炸制食材', description: '油温六成热，分别将土豆、茄子、青椒炸至金黄捞出。（茄子炸前挤干水分再裹薄淀粉）', image: stepImg('地三鲜', 2, '炸茄子土豆') },
      { step: 3, title: '烧制调味', description: '锅中留少许底油，下蒜末爆香，加入生抽、老抽、糖和少许水，下入炸好的三样食材快速翻炒均匀，勾薄芡即可出锅。', image: stepImg('地三鲜', 3, '地三鲜成品') },
    ],
  },
  {
    id: 'd9', name: '糖醋里脊', category: '家常菜', emoji: '🍖', liked: true,
    tags: ['甜酸', '孩子爱', '外酥里嫩'],
    addedAt: '2026-01-01',
    image: cover('糖醋里脊'),
    prepTime: '15分钟', cookTime: '15分钟', servings: 3,
    difficulty: '中等',
    description: '外酥里嫩，酸甜可口，大人小孩都爱',
    ingredients: ['里脊肉 400g', '鸡蛋 1个', '淀粉 适量', '番茄酱 3勺', '白醋 2勺', '糖 2勺', '白芝麻 少许'],
    steps: [
      { step: 1, title: '切条腌制', description: '里脊肉切成长条，加盐、料酒、蛋清抓匀腌制15分钟，裹上干淀粉。', image: stepImg('里脊肉', 1, '切里脊条') },
      { step: 2, title: '炸制定型', description: '油温六成热，下肉条炸至定型金黄，捞出。油温升高后复炸一次使其更加酥脆，捞出备用。', image: stepImg('里脊', 2, '炸里脊') },
      { step: 3, title: '调糖醋汁', description: '番茄酱、白醋、糖、少许水调匀。', image: stepImg('糖醋里脊', 3, '调糖醋汁') },
      { step: 4, title: '裹汁出锅', description: '热锅倒入糖醋汁烧开冒泡，下入炸好的里脊快速翻匀裹满酱汁，撒白芝麻出锅。', image: stepImg('糖醋里脊', 4, '糖醋里脊成品') },
    ],
  },
  {
    id: 'd10', name: '回锅肉', category: '家常菜', emoji: '🥓', liked: true,
    tags: ['香', '下饭', '川味'],
    addedAt: '2026-01-01',
    image: cover('回锅肉'),
    prepTime: '15分钟', cookTime: '20分钟', servings: 3,
    difficulty: '中等',
    description: '肥而不腻，香气扑鼻的经典川菜',
    ingredients: ['五花肉 300g', '蒜苗 3根', '郫县豆瓣酱 1.5勺', '甜面酱 1勺', '豆豉 少许', '糖 半勺', '姜片 3片', '料酒 1勺'],
    steps: [
      { step: 1, title: '煮五花肉', description: '五花肉整块冷水下锅，加姜片、料酒煮30分钟至八成熟，捞出放凉切薄片。', image: stepImg('五花肉', 1, '煮五花肉') },
      { step: 2, title: '煸炒肉片', description: '锅中少许油，下入肉片小火慢慢煸炒，煸出油脂至肉片卷曲微焦。', image: stepImg('回锅肉', 2, '煸炒肉片') },
      { step: 3, title: '加入调料', description: '肉片推到一边，下豆瓣酱、豆豉、甜面酱炒出红油，下蒜苗段翻炒。', image: stepImg('回锅肉', 3, '加豆瓣酱') },
      { step: 4, title: '调味出锅', description: '加糖调味，蒜苗断生后即可出锅装盘。', image: stepImg('回锅肉', 4, '回锅肉成品') },
    ],
  },

  // ========== 川菜 ==========
  {
    id: 'd11', name: '麻婆豆腐', category: '川菜', emoji: '🌶️', liked: true,
    tags: ['麻辣', '下饭', '经典'],
    addedAt: '2026-01-01',
    image: cover('麻婆豆腐'),
    prepTime: '10分钟', cookTime: '15分钟', servings: 3,
    difficulty: '简单',
    description: '麻、辣、烫、鲜、香，川菜代表作',
    ingredients: ['嫩豆腐 1盒', '牛肉末 100g', '郫县豆瓣酱 1.5勺', '花椒粉 1茶匙', '蒜末 适量', '姜末 适量', '生抽 1勺', '水淀粉 适量', '葱花 少许'],
    steps: [
      { step: 1, title: '处理豆腐', description: '豆腐切2cm方块，焯水2分钟去豆腥，捞出备用。', image: stepImg('豆腐', 1, '切豆腐块') },
      { step: 2, title: '炒肉末', description: '热锅宽油，下牛肉末炒散炒干水分，加姜末、蒜末、豆瓣酱炒出红油。', image: stepImg('麻婆豆腐', 2, '炒肉末') },
      { step: 3, title: '烧豆腐', description: '加入适量清水或高汤，下豆腐块，轻轻推动，加生抽调味，中小火烧3分钟入味。', image: stepImg('麻婆豆腐', 3, '烧豆腐') },
      { step: 4, title: '勾芡出锅', description: '分两次淋入水淀粉勾芡，使汤汁浓稠挂在豆腐上，撒花椒粉和葱花即可出锅。', image: stepImg('麻婆豆腐', 4, '麻婆豆腐成品') },
    ],
  },
  {
    id: 'd12', name: '水煮牛肉', category: '川菜', emoji: '🐄', liked: true,
    tags: ['麻辣', '嫩滑', '宴客'],
    addedAt: '2026-01-01',
    image: cover('水煮牛肉'),
    prepTime: '20分钟', cookTime: '15分钟', servings: 4,
    difficulty: '困难',
    description: '麻辣鲜烫，牛肉嫩滑，川菜经典',
    ingredients: ['牛里脊 400g', '豆芽 200g', '莴笋 1根', '郫县豆瓣酱 2勺', '干辣椒 10个', '花椒 1把', '蒜末 适量', '姜末 适量', '生抽 1勺', '淀粉 适量', '蛋清 1个'],
    steps: [
      { step: 1, title: '腌制牛肉', description: '牛肉逆纹切薄片，加盐、料酒、蛋清、淀粉抓匀腌制20分钟。', image: stepImg('牛肉', 1, '切牛肉片') },
      { step: 2, title: '烫蔬菜垫底', description: '豆芽、莴笋片分别焯水铺在碗底。', image: stepImg('水煮牛肉', 2, '豆芽垫底') },
      { step: 3, title: '煮牛肉', description: '锅中烧水或高汤，加豆瓣酱、姜末、生抽，下牛肉片快速滑散，牛肉变色立即捞出铺在蔬菜上。', image: stepImg('水煮牛肉', 3, '烫牛肉') },
      { step: 4, title: '激香出锅', description: '在牛肉上放蒜末、干辣椒段、花椒，热油浇在调料上激出香味即可。', image: stepImg('水煮牛肉', 4, '水煮牛肉成品') },
    ],
  },
  {
    id: 'd13', name: '辣子鸡', category: '川菜', emoji: '🔥', liked: true,
    tags: ['麻辣', '香脆', '下酒'],
    addedAt: '2026-01-01',
    image: cover('辣子鸡'),
    prepTime: '15分钟', cookTime: '20分钟', servings: 3,
    difficulty: '中等',
    description: '干辣椒里找鸡块，外酥里嫩麻辣香',
    ingredients: ['鸡腿肉 500g', '干辣椒 80g', '花椒 2勺', '姜片 5片', '蒜片 适量', '白芝麻 1勺', '生抽 1勺', '盐 适量', '淀粉 适量'],
    steps: [
      { step: 1, title: '切块腌制', description: '鸡腿肉切2cm小块，加盐、料酒、生抽、淀粉抓匀腌制20分钟。', image: stepImg('鸡肉', 1, '切鸡块') },
      { step: 2, title: '炸制鸡肉', description: '油温六成热，下鸡块炸至定型，捞出。油温升高后复炸至金黄酥脆，捞出备用。', image: stepImg('辣子鸡', 2, '炸鸡块') },
      { step: 3, title: '爆炒香辣', description: '锅中留少许油，下干辣椒、花椒、姜蒜片小火炒出香味，倒入炸好的鸡块快速翻匀。', image: stepImg('辣子鸡', 3, '炒干辣椒') },
      { step: 4, title: '出锅装盘', description: '撒白芝麻翻匀出锅，辣椒花椒越多越香。', image: stepImg('辣子鸡', 4, '辣子鸡成品') },
    ],
  },
  {
    id: 'd14', name: '毛血旺', category: '川菜', emoji: '🩸', liked: false,
    tags: ['麻辣', '内脏', '聚餐'],
    addedAt: '2026-01-01',
    image: cover('毛血旺'),
    prepTime: '20分钟', cookTime: '15分钟', servings: 4,
    difficulty: '中等',
    description: '毛肚鸭血配素菜，麻辣鲜香一锅端',
    ingredients: ['鸭血 200g', '毛肚 150g', '黄喉 100g', '豆芽 100g', '藕片 100g', '郫县豆瓣酱 2勺', '干辣椒 10个', '花椒 1把', '火锅底料 50g', '蒜末 适量', '盐 适量'],
    steps: [
      { step: 1, title: '处理食材', description: '毛肚切条、黄喉切段、鸭血切厚片，豆芽、藕片洗净备用。', image: stepImg('毛血旺', 1, '备料毛血旺') },
      { step: 2, title: '炒底料', description: '锅中少许油，下豆瓣酱、火锅底料小火炒出红油，加水烧开。', image: stepImg('毛血旺', 2, '炒火锅底料') },
      { step: 3, title: '烫煮食材', description: '先下豆芽、藕片煮熟捞出铺碗底，再下毛肚、黄喉、鸭血烫熟捞出。', image: stepImg('毛血旺', 3, '烫食材') },
      { step: 4, title: '激香淋油', description: '碗中放蒜末、干辣椒段、花椒，热油浇上激香即可。', image: stepImg('毛血旺', 4, '毛血旺成品') },
    ],
  },
  {
    id: 'd15', name: '干锅花菜', category: '川菜', emoji: '🥦', liked: false,
    tags: ['香辣', '干香', '下饭'],
    addedAt: '2026-01-01',
    image: cover('干锅花菜'),
    prepTime: '10分钟', cookTime: '10分钟', servings: 2,
    difficulty: '简单',
    description: '花菜干香入味，麻辣开胃',
    ingredients: ['有机花菜 1颗', '五花肉 100g', '郫县豆瓣酱 1勺', '干辣椒 5个', '花椒 10粒', '蒜片 适量', '生抽 1勺', '糖 半勺'],
    steps: [
      { step: 1, title: '处理花菜', description: '花菜掰成小朵，浸泡洗净。热锅不放油，干锅煸炒花菜至微微焦香盛出。', image: stepImg('花菜', 1, '掰花菜') },
      { step: 2, title: '煸炒肉片', description: '锅中少许油，下五花肉片煸出油脂至焦脆。', image: stepImg('干锅花菜', 2, '煸五花肉') },
      { step: 3, title: '合炒调味', description: '下豆瓣酱、干辣椒、蒜片炒香，倒入花菜快速翻炒，加生抽、糖调味，炒至入味即可出锅。', image: stepImg('干锅花菜', 3, '干锅花菜成品') },
    ],
  },
  {
    id: 'd34', name: '酸菜鱼', category: '川菜', emoji: '🐟', liked: true,
    tags: ['酸辣', '鱼片', '下饭'],
    addedAt: '2026-01-01',
    image: cover('酸菜鱼'),
    prepTime: '20分钟', cookTime: '15分钟', servings: 4,
    difficulty: '中等',
    description: '酸辣开胃，鱼片嫩滑',
    ingredients: ['黑鱼/草鱼 1条', '酸菜 200g', '泡椒 5个', '姜片 5片', '蒜末 适量', '干辣椒 5个', '花椒 1小把', '蛋清 1个', '淀粉 适量', '盐 适量', '白醋 1勺'],
    steps: [
      { step: 1, title: '处理鱼肉', description: '鱼肉片成薄片，加盐、料酒、蛋清、淀粉抓匀腌制15分钟。鱼骨和鱼头切块备用。', image: stepImg('酸菜鱼', 1, '片鱼片') },
      { step: 2, title: '炒酸菜底', description: '锅中少许油，下酸菜、泡椒、姜片炒香，加水或高汤烧开。', image: stepImg('酸菜鱼', 2, '炒酸菜') },
      { step: 3, title: '煮鱼片', description: '汤中下鱼骨煮5分钟，下鱼片轻轻滑散，2分钟即熟，加白醋调味。', image: stepImg('酸菜鱼', 3, '下鱼片') },
      { step: 4, title: '激香出锅', description: '碗底铺生菜或豆芽，将鱼汤鱼肉盛入，放蒜末、干辣椒段、花椒，热油浇上激香即可。', image: stepImg('酸菜鱼', 4, '酸菜鱼成品') },
    ],
  },

  // ========== 粤菜 ==========
  {
    id: 'd16', name: '白切鸡', category: '粤菜', emoji: '🐓', liked: true,
    tags: ['清淡', '鲜嫩', '经典'],
    addedAt: '2026-01-01',
    image: cover('白切鸡'),
    prepTime: '10分钟', cookTime: '30分钟', servings: 4,
    difficulty: '简单',
    description: '皮爽肉滑，保持鸡的原汁原味',
    ingredients: ['三黄鸡 1只（约1.5kg）', '姜片 5片', '葱段 3段', '料酒 2勺', '盐 适量', '沙姜 1块', '花生油 2勺'],
    steps: [
      { step: 1, title: '浸泡鸡肉', description: '三黄鸡处理干净，整只放入没过鸡肉的冷水锅中，加姜片、葱段、料酒。', image: stepImg('白切鸡', 1, '整鸡下锅') },
      { step: 2, title: '小火浸熟', description: '大火烧开后立即关火，盖盖子浸30分钟（利用余温把鸡肉浸熟，这样鸡肉特别嫩）。', image: stepImg('白切鸡', 2, '浸熟鸡肉') },
      { step: 3, title: '过冷河', description: '捞出浸好的鸡，放入冰水中浸泡5分钟，使鸡皮爽脆。', image: stepImg('白切鸡', 3, '冰水浸泡') },
      { step: 4, title: '切块蘸料', description: '鸡沥干水分，斩块装盘。沙姜切末，加盐、热花生油调成蘸料搭配食用。', image: stepImg('白切鸡', 4, '白切鸡成品') },
    ],
  },
  {
    id: 'd17', name: '蒜蓉粉丝蒸扇贝', category: '粤菜', emoji: '🦐', liked: true,
    tags: ['海鲜', '鲜嫩', '精致'],
    addedAt: '2026-01-01',
    image: cover('蒜蓉粉丝蒸扇贝'),
    prepTime: '15分钟', cookTime: '10分钟', servings: 4,
    difficulty: '中等',
    description: '扇贝鲜甜，粉丝吸满蒜蓉汁水',
    ingredients: ['扇贝 8个', '粉丝 50g', '蒜末 3勺', '生抽 1勺', '蚝油 1勺', '糖 半勺', '小米辣 2个', '葱花 少许', '油 适量'],
    steps: [
      { step: 1, title: '处理扇贝', description: '扇贝撬开取肉，洗净黑肠，粉丝用温水泡软备用。', image: stepImg('扇贝', 1, '处理扇贝') },
      { step: 2, title: '铺底摆盘', description: '每个扇贝壳上铺一层粉丝，放上扇贝肉。', image: stepImg('蒸扇贝', 2, '摆盘扇贝') },
      { step: 3, title: '炒蒜蓉酱', description: '热油下蒜末炒香，加生抽、蚝油、糖、小米辣圈调成酱汁，淋在扇贝上。', image: stepImg('蒜蓉扇贝', 3, '炒蒜蓉') },
      { step: 4, title: '蒸制出锅', description: '水开后上锅蒸5分钟，出锅撒葱花，淋上热油即可。', image: stepImg('蒜蓉蒸扇贝', 4, '蒸扇贝成品') },
    ],
  },
  {
    id: 'd18', name: '清蒸鲈鱼', category: '粤菜', emoji: '🐟', liked: true,
    tags: ['清淡', '鲜嫩', '健康'],
    addedAt: '2026-01-01',
    image: cover('清蒸鲈鱼'),
    prepTime: '10分钟', cookTime: '10分钟', servings: 3,
    difficulty: '简单',
    description: '鱼肉鲜嫩，清淡营养',
    ingredients: ['鲈鱼 1条（约500g）', '葱丝 适量', '姜丝 适量', '蒸鱼豉油 2勺', '料酒 1勺', '热油 2勺'],
    steps: [
      { step: 1, title: '处理鲈鱼', description: '鲈鱼处理干净，鱼身两面各划3刀，抹上料酒和少许盐，肚子里放姜片，表面铺葱段。', image: stepImg('鲈鱼', 1, '处理鲈鱼') },
      { step: 2, title: '入锅蒸制', description: '水开后放入鲈鱼，大火蒸8~10分钟（视鱼大小而定），鱼眼凸出即熟。', image: stepImg('清蒸鱼', 2, '清蒸鲈鱼') },
      { step: 3, title: '出锅淋汁', description: '倒掉蒸出的腥水，换上新葱丝，淋上蒸鱼豉油，最后浇上热油即可上桌。', image: stepImg('清蒸鲈鱼', 3, '淋汁蒸鱼') },
    ],
  },
  {
    id: 'd19', name: '叉烧', category: '粤菜', emoji: '🍖', liked: false,
    tags: ['甜香', '宴客', '经典'],
    addedAt: '2026-01-01',
    image: cover('叉烧'),
    prepTime: '10分钟', cookTime: '30分钟（腌制过夜）', servings: 4,
    difficulty: '中等',
    description: '广式经典，烧腊店招牌',
    ingredients: ['梅花肉/里脊 600g', '叉烧酱 3勺', '蜂蜜 2勺', '生抽 1勺', '老抽 半勺', '蚝油 1勺', '红曲粉 半勺（上色用）'],
    steps: [
      { step: 1, title: '腌制入味', description: '肉切成长条，所有调料混合均匀，倒入肉中抓匀，冷藏腌制过夜（至少4小时）。', image: stepImg('叉烧', 1, '腌制叉烧') },
      { step: 2, title: '烤制叉烧', description: '烤箱预热200°C，烤盘铺锡纸放上腌好的肉，烤20分钟，中途翻面并刷腌料汁。', image: stepImg('叉烧', 2, '烤叉烧') },
      { step: 3, title: '上色焦香', description: '最后5分钟开上火，使表面焦糖化。出炉后切厚片即可。', image: stepImg('叉烧', 3, '叉烧成品') },
    ],
  },
  {
    id: 'd20', name: '煲仔饭', category: '粤菜', emoji: '🍚', liked: true,
    tags: ['主食', '香脆', '经典'],
    addedAt: '2026-01-01',
    image: cover('煲仔饭'),
    prepTime: '15分钟', cookTime: '30分钟', servings: 2,
    difficulty: '中等',
    description: '米饭锅巴香脆，腊味鲜美',
    ingredients: ['大米 200g', '腊肠 2根', '腊肉 50g', '鸡蛋 1个', '青菜 2棵', '生抽 2勺', '蚝油 1勺', '糖 半勺', '油 适量'],
    steps: [
      { step: 1, title: '泡米铺料', description: '大米洗净浸泡30分钟，腊肠、腊肉切片。砂锅底刷一层油，铺上米加水，水开后转小火。', image: stepImg('煲仔饭', 1, '砂锅煮饭') },
      { step: 2, title: '铺肉焖饭', description: '米饭七成熟时（表面还有少许水），铺上腊肠腊肉片，中间打一个鸡蛋，盖盖继续小火焖10分钟。', image: stepImg('煲仔饭', 2, '铺腊味鸡蛋') },
      { step: 3, title: '淋汁出锅', description: '青菜焯熟铺在旁边，生抽、蚝油、糖调匀淋在饭上，拌匀即可享用锅巴。', image: stepImg('煲仔饭', 3, '煲仔饭成品') },
    ],
  },

  // ========== 日料 ==========
  {
    id: 'd21', name: '三文鱼刺身', category: '日料', emoji: '🍣', liked: true,
    tags: ['生食', '精致', '清淡'],
    addedAt: '2026-01-01',
    image: cover('三文鱼刺身'),
    prepTime: '10分钟', cookTime: '0分钟', servings: 2,
    difficulty: '简单',
    description: '新鲜三文鱼，蘸芥末酱油食用',
    ingredients: ['新鲜三文鱼刺身级 200g', '芥末 适量', '酱油 适量', '柠檬片 少许'],
    steps: [
      { step: 1, title: '选购处理', description: '购买刺身级新鲜三文鱼，用厨房纸吸干表面水分。', image: stepImg('三文鱼', 1, '三文鱼刺身') },
      { step: 2, title: '切片摆盘', description: '用锋利的刀将鱼肉切成约5mm厚的长片，摆在冰镇的盘子上。', image: stepImg('刺身', 2, '切三文鱼') },
      { step: 3, title: '搭配蘸料', description: '芥末放于鱼片上，酱油倒入蘸碟，食用时夹起鱼片轻沾酱油即可。', image: stepImg('三文鱼刺身', 3, '刺身摆盘') },
    ],
  },
  {
    id: 'd22', name: '日式炸猪排', category: '日料', emoji: '🥩', liked: false,
    tags: ['香脆', '厚实', '孩子爱'],
    addedAt: '2026-01-01',
    image: cover('日式炸猪排'),
    prepTime: '10分钟', cookTime: '15分钟', servings: 2,
    difficulty: '中等',
    description: '外酥里嫩，配米饭和猪排酱汁',
    ingredients: ['猪里脊/梅花肉 2块', '面粉 适量', '鸡蛋 1个', '面包糠 适量', '盐 黑胡椒 适量', '卷心菜丝 适量', '猪排酱 适量'],
    steps: [
      { step: 1, title: '处理猪排', description: '猪排用肉锤或刀背敲松，两面撒盐和黑胡椒腌5分钟。', image: stepImg('猪排', 1, '处理猪排') },
      { step: 2, title: '裹粉三步', description: '依次裹上面粉 → 蛋液 → 面包糠，按实备用。', image: stepImg('炸猪排', 2, '裹面包糠') },
      { step: 3, title: '油炸', description: '油温160°C，下猪排炸4分钟翻面再炸4分钟，捞出。油温升高后复炸30秒至金黄酥脆。', image: stepImg('日式炸猪排', 3, '炸猪排') },
      { step: 4, title: '切块装盘', description: '捞出沥油，切成宽条，配卷心菜丝和猪排酱即可。', image: stepImg('日式炸猪排', 4, '猪排饭成品') },
    ],
  },
  {
    id: 'd23', name: '味噌汤', category: '日料', emoji: '🍲', liked: false,
    tags: ['汤类', '清淡', '开胃'],
    addedAt: '2026-01-01',
    image: cover('味噌汤'),
    prepTime: '10分钟', cookTime: '10分钟', servings: 3,
    difficulty: '简单',
    description: '日式经典汤品，暖胃营养',
    ingredients: ['嫩豆腐 半块', '海带 5cm段', '味噌酱 2勺', '小葱 适量', '木鱼花 少许', '水 600ml'],
    steps: [
      { step: 1, title: '煮海带汤底', description: '水中放入海带段，小火煮5分钟取出海带，留下鲜汤。', image: stepImg('味噌汤', 1, '煮海带汤') },
      { step: 2, title: '加入豆腐', description: '嫩豆腐切小方块，轻轻放入汤中煮2分钟。', image: stepImg('味噌汤', 2, '下豆腐') },
      { step: 3, title: '加味噌出锅', description: '关小火，将味噌酱放入漏勺中，用筷子在汤里搅拌使味噌融化溶入汤中，撒葱花即可出锅。', image: stepImg('味噌汤', 3, '味噌汤成品') },
    ],
  },

  // ========== 火锅 ==========
  {
    id: 'd24', name: '牛肉火锅', category: '火锅', emoji: '🫕', liked: true,
    tags: ['聚餐', '暖身', '丰盛'],
    addedAt: '2026-01-01',
    image: cover('牛肉火锅'),
    prepTime: '30分钟', cookTime: '40分钟', servings: 4,
    difficulty: '中等',
    description: '鲜嫩牛肉搭配丰富配菜，热气腾腾',
    ingredients: ['肥牛片 400g', '牛肉卷 300g', '金针菇 200g', '豆腐 1块', '白菜 适量', '土豆片 适量', '粉丝 适量', '芝麻酱蘸料 适量', '沙茶酱 适量', '菌菇拼盘 适量'],
    steps: [
      { step: 1, title: '准备锅底', description: '锅中加水，放入党参、红枣、枸杞、姜片做成清汤锅底，或用麻辣火锅底料做成红油锅底。', image: stepImg('火锅', 1, '煮火锅底料') },
      { step: 2, title: '处理配菜', description: '所有蔬菜洗净切好，豆腐切块，白菜撕大片，金针菇去根洗净。', image: stepImg('牛肉火锅', 2, '备菜摆盘') },
      { step: 3, title: '边涮边吃', description: '锅底烧开后，先涮牛肉（变色即熟），再涮各类蔬菜豆腐，粉丝最后下。', image: stepImg('涮火锅', 3, '涮肥牛') },
      { step: 4, title: '蘸料享用', description: '肥牛蘸麻酱，蔬菜蘸沙茶酱，各有风味。最后下一把粉丝，收尾汤底最鲜。', image: stepImg('火锅蘸料', 4, '火锅蘸料') },
    ],
  },
  {
    id: 'd25', name: '串串香', category: '火锅', emoji: '🍢', liked: false,
    tags: ['小食', '聚餐', '麻辣'],
    addedAt: '2026-01-01',
    image: cover('串串香'),
    prepTime: '30分钟', cookTime: '20分钟', servings: 4,
    difficulty: '简单',
    description: '各种食材串签涮煮，自在随意',
    ingredients: ['牛肉片 200g', '鸡翅 6个', '虾仁 100g', '各类丸子 300g', '蔬菜串（香菇、藕片、土豆片、青椒）', '火锅底料 1包', '签子 适量'],
    steps: [
      { step: 1, title: '准备签子', description: '将食材分别穿在竹签上，牛肉可以卷起来穿，虾仁整只穿，鸡翅切两半穿。', image: stepImg('串串香', 1, '串食材') },
      { step: 2, title: '煮锅底', description: '锅中加水，放入火锅底料煮开，散发出麻辣香味。', image: stepImg('串串', 2, '煮锅底串串') },
      { step: 3, title: '涮煮食材', description: '各种签子放入锅中涮煮，肉类变色即熟，蔬菜2~3分钟，丸子5分钟。', image: stepImg('串串香', 3, '串串香成品') },
    ],
  },

  // ========== 面食 ==========
  {
    id: 'd26', name: '红油抄手', category: '面食', emoji: '🥟', liked: true,
    tags: ['麻辣', '开胃', '快手'],
    addedAt: '2026-01-01',
    image: cover('红油抄手'),
    prepTime: '20分钟', cookTime: '5分钟', servings: 2,
    difficulty: '中等',
    description: '四川经典小吃，皮薄馅嫩，红油飘香',
    ingredients: ['馄饨皮 200g', '猪肉末 200g', '姜末 适量', '生抽 1勺', '盐 适量', '花椒粉 少许', '红油 2勺', '蒜末 1勺', '芝麻 1勺', '葱花 适量', '紫菜 少许'],
    steps: [
      { step: 1, title: '调制肉馅', description: '猪肉末加姜末、生抽、盐、花椒粉搅拌上劲。', image: stepImg('红油抄手', 1, '调肉馅') },
      { step: 2, title: '包馄饨', description: '取馄饨皮，包入肉馅，对折捏紧，两角弯向捏合即成。', image: stepImg('馄饨', 2, '包馄饨') },
      { step: 3, title: '煮馄饨', description: '锅中烧水，水开后下馄饨煮至浮起（约3分钟），捞出过凉水沥干。', image: stepImg('红油抄手', 3, '煮馄饨') },
      { step: 4, title: '调汁装碗', description: '碗中放红油、蒜末、芝麻、生抽，将馄饨盛入，拌匀即可享用。', image: stepImg('红油抄手', 4, '红油抄手成品') },
    ],
  },
  {
    id: 'd27', name: '阳春面', category: '面食', emoji: '🍜', liked: true,
    tags: ['清淡', '快手', '早餐'],
    addedAt: '2026-01-01',
    image: cover('阳春面'),
    prepTime: '5分钟', cookTime: '8分钟', servings: 1,
    difficulty: '简单',
    description: '一碗清汤素面，朴素中见真味',
    ingredients: ['细面条 100g', '生抽 1勺', '猪油 半勺', '葱花 适量', '盐 适量', '白胡椒粉 少许', '开水 适量'],
    steps: [
      { step: 1, title: '煮面条', description: '锅中烧水，水开后下入细面条，煮至面条无硬心（约3分钟）。', image: stepImg('阳春面', 1, '煮面条') },
      { step: 2, title: '调碗底', description: '碗中放生抽、猪油、葱花、盐、白胡椒粉备用。', image: stepImg('阳春面', 2, '阳春面碗底') },
      { step: 3, title: '冲汤拌面', description: '碗中冲入半碗面条汤搅匀化开，捞入面条拌匀即可享用。', image: stepImg('阳春面', 3, '阳春面成品') },
    ],
  },
  {
    id: 'd28', name: '肉夹馍', category: '面食', emoji: '🥙', liked: false,
    tags: ['西北', '香', '主食'],
    addedAt: '2026-01-01',
    image: cover('肉夹馍'),
    prepTime: '30分钟', cookTime: '120分钟', servings: 4,
    difficulty: '困难',
    description: '白吉馍夹腊汁肉，陕西名吃',
    ingredients: ['中筋面粉 400g', '酵母 3g', '五花肉 500g', '冰糖 20g', '生抽 2勺', '老抽 1勺', '八角 2个', '桂皮 1小块', '香叶 2片', '草果 1个', '盐 适量'],
    steps: [
      { step: 1, title: '发面做饼', description: '面粉加酵母、温水揉成光滑面团，醒发1小时，分成小剂子擀成长条卷起，再压扁成饼胚。', image: stepImg('肉夹馍', 1, '做饼胚') },
      { step: 2, title: '烙白吉馍', description: '平底锅小火将饼胚烙至两面微黄定型，再放入烤箱或电饼铛烙熟。', image: stepImg('白吉馍', 2, '烙饼') },
      { step: 3, title: '炖腊汁肉', description: '五花肉切大块，冷水下锅焯水。另起锅炒糖色，下肉块翻炒，加所有香料、生抽、老抽、盐，加水没过肉大火烧开转小火炖2小时至酥烂。', image: stepImg('肉夹馍', 3, '炖腊汁肉') },
      { step: 4, title: '夹馍享用', description: '白吉馍从中间切开，夹入切碎的腊汁肉，浇上少许汤汁即可。', image: stepImg('肉夹馍', 4, '肉夹馍成品') },
    ],
  },

  // ========== 烧烤 ==========
  {
    id: 'd29', name: '烤羊肉串', category: '烧烤', emoji: '🍢', liked: true,
    tags: ['香', '聚会', '下酒'],
    addedAt: '2026-01-01',
    image: cover('烤羊肉串'),
    prepTime: '20分钟', cookTime: '10分钟', servings: 4,
    difficulty: '简单',
    description: '外焦里嫩，孜然飘香',
    ingredients: ['羊腿肉 500g', '孜然粉 1勺', '孜然粒 1勺', '辣椒粉 1勺', '盐 适量', '生抽 1勺', '油 1勺', '洋葱半个', '竹签 适量'],
    steps: [
      { step: 1, title: '切块腌制', description: '羊肉切3cm方块，洋葱切丝，加盐、生抽、油、孜然粉腌制30分钟以上。', image: stepImg('羊肉串', 1, '切羊肉块') },
      { step: 2, title: '穿串', description: '竹签提前泡水，将羊肉块肥瘦相间穿在签子上。', image: stepImg('羊肉串', 2, '穿羊肉串') },
      { step: 3, title: '烤制', description: '炭火或烤箱200°C，烤10分钟，中途翻面，刷一层油，撒孜然粉、辣椒粉，出炉后再撒孜然粒即可。', image: stepImg('烤羊肉串', 3, '烤羊肉串') },
    ],
  },
  {
    id: 'd30', name: '烤生蚝', category: '烧烤', emoji: '🦪', liked: false,
    tags: ['海鲜', '鲜香', '聚会'],
    addedAt: '2026-01-01',
    image: cover('烤生蚝'),
    prepTime: '10分钟', cookTime: '10分钟', servings: 4,
    difficulty: '简单',
    description: '蒜蓉粉丝烤生蚝，鲜美多汁',
    ingredients: ['生蚝 8只', '粉丝 30g', '蒜末 3勺', '小米辣 2个', '生抽 1勺', '蚝油 1勺', '糖 半勺', '葱花 适量', '油 适量'],
    steps: [
      { step: 1, title: '处理生蚝', description: '生蚝撬开取肉，洗净泥沙，粉丝泡软备用。', image: stepImg('生蚝', 1, '处理生蚝') },
      { step: 2, title: '炒蒜蓉', description: '热油下蒜末炒香，加小米辣、生抽、蚝油、糖调成蒜蓉酱。', image: stepImg('烤生蚝', 2, '炒蒜蓉') },
      { step: 3, title: '组装烤制', description: '每个生蚝壳上放泡好的粉丝，放上生蚝肉，舀上蒜蓉酱。烤箱200°C烤10分钟，出炉撒葱花即可。', image: stepImg('烤生蚝', 3, '烤生蚝成品') },
    ],
  },

  // ========== 其他 ==========
  {
    id: 'd31', name: '黄焖鸡米饭', category: '其他', emoji: '🍗', liked: true,
    tags: ['快餐', '下饭', '实惠'],
    addedAt: '2026-01-01',
    image: cover('黄焖鸡'),
    prepTime: '15分钟', cookTime: '30分钟', servings: 3,
    difficulty: '简单',
    description: '鸡肉软嫩，汤汁浓郁，配米饭绝配',
    ingredients: ['鸡腿肉 500g', '香菇 5朵', '青椒 1个', '土豆 1个', '干辣椒 3个', '姜片 3片', '生抽 2勺', '老抽 1勺', '蚝油 1勺', '冰糖 5g', '黄焖鸡酱 2勺'],
    steps: [
      { step: 1, title: '切块腌制', description: '鸡腿肉切块，加生抽、料酒腌制10分钟。香菇切片，土豆、青椒切块备用。', image: stepImg('黄焖鸡', 1, '切鸡块') },
      { step: 2, title: '炒香调料', description: '锅中少许油，下冰糖炒至微黄，下鸡块翻炒上色，加姜片、干辣椒、香菇片炒香。', image: stepImg('黄焖鸡', 2, '炒香调料') },
      { step: 3, title: '焖煮', description: '加生抽、老抽、蚝油、黄焖鸡酱，加开水没过鸡块，放土豆块，大火烧开转小火焖20分钟。', image: stepImg('黄焖鸡', 3, '焖煮黄焖鸡') },
      { step: 4, title: '加蔬菜出锅', description: '下青椒块翻匀，大火收汁至浓稠，配白米饭即可享用。', image: stepImg('黄焖鸡米饭', 4, '黄焖鸡成品') },
    ],
  },
  {
    id: 'd32', name: '蛋炒饭', category: '其他', emoji: '🍚', liked: true,
    tags: ['快手', '家常', '主食'],
    addedAt: '2026-01-01',
    image: cover('蛋炒饭'),
    prepTime: '5分钟', cookTime: '5分钟', servings: 1,
    difficulty: '简单',
    description: '粒粒分明，金黄喷香',
    ingredients: ['隔夜冷饭 1碗', '鸡蛋 2个', '葱花 适量', '盐 适量', '油 适量'],
    steps: [
      { step: 1, title: '打蛋炒蛋', description: '鸡蛋打散。锅中宽油烧热，下蛋液快速炒散成金黄蛋碎，盛出备用。', image: stepImg('蛋炒饭', 1, '炒鸡蛋碎') },
      { step: 2, title: '炒米饭', description: '锅中再加油，下米饭快速翻炒，用锅铲压散结块的米饭。', image: stepImg('蛋炒饭', 2, '炒米饭') },
      { step: 3, title: '合炒调味', description: '倒入鸡蛋碎，加盐调味，撒葱花翻炒均匀，出锅装盘。', image: stepImg('蛋炒饭', 3, '蛋炒饭成品') },
    ],
  },
  {
    id: 'd33', name: '冬瓜排骨汤', category: '其他', emoji: '🍲', liked: false,
    tags: ['清淡', '养生', '汤类'],
    addedAt: '2026-01-01',
    image: cover('冬瓜排骨汤'),
    prepTime: '15分钟', cookTime: '90分钟', servings: 4,
    difficulty: '简单',
    description: '清淡鲜美，夏日消暑佳品',
    ingredients: ['排骨 500g', '冬瓜 500g', '姜片 5片', '料酒 1勺', '盐 适量', '葱花 少许'],
    steps: [
      { step: 1, title: '处理排骨', description: '排骨切小段，冷水下锅焯水去血沫，捞出洗净备用。', image: stepImg('排骨', 1, '排骨焯水') },
      { step: 2, title: '炖排骨', description: '锅中加足量水，下排骨和姜片、料酒，大火烧开后转小火炖60分钟。', image: stepImg('排骨汤', 2, '炖排骨') },
      { step: 3, title: '加冬瓜', description: '冬瓜去皮切厚块，加入汤中继续炖20分钟至冬瓜软烂透明。', image: stepImg('冬瓜排骨汤', 3, '加冬瓜') },
      { step: 4, title: '调味出锅', description: '加盐调味，撒葱花即可出锅享用。', image: stepImg('冬瓜排骨汤', 4, '排骨汤成品') },
    ],
  },
];
